/**
 * Country dial codes for the booking phone field.
 * Code is without + (e.g. "39"); store as +39 1234567890.
 */

export type PhoneCountry = { code: string; country: string };

export const PHONE_COUNTRY_CODES: PhoneCountry[] = [
  { code: "39", country: "Italia" },
  { code: "33", country: "Francia" },
  { code: "49", country: "Germania" },
  { code: "34", country: "Spagna" },
  { code: "44", country: "Regno Unito" },
  { code: "212", country: "Marocco" },
  { code: "213", country: "Algeria" },
  { code: "216", country: "Tunisia" },
  { code: "20", country: "Egitto" },
  { code: "40", country: "Romania" },
  { code: "355", country: "Albania" },
  { code: "381", country: "Serbia" },
  { code: "386", country: "Slovenia" },
  { code: "387", country: "Bosnia ed Erzegovina" },
  { code: "389", country: "Macedonia del Nord" },
  { code: "383", country: "Kosovo" },
  { code: "382", country: "Montenegro" },
  { code: "385", country: "Croazia" },
  { code: "30", country: "Grecia" },
  { code: "90", country: "Turchia" },
  { code: "234", country: "Nigeria" },
  { code: "221", country: "Senegal" },
  { code: "223", country: "Mali" },
  { code: "224", country: "Guinea" },
  { code: "225", country: "Costa d'Avorio" },
  { code: "226", country: "Burkina Faso" },
  { code: "227", country: "Niger" },
  { code: "228", country: "Togo" },
  { code: "229", country: "Benin" },
  { code: "230", country: "Mauritius" },
  { code: "92", country: "Pakistan" },
  { code: "880", country: "Bangladesh" },
  { code: "91", country: "India" },
  { code: "86", country: "Cina" },
  { code: "7", country: "Russia" },
  { code: "380", country: "Ucraina" },
  { code: "48", country: "Polonia" },
  { code: "32", country: "Belgio" },
  { code: "31", country: "Paesi Bassi" },
  { code: "41", country: "Svizzera" },
  { code: "43", country: "Austria" },
  { code: "351", country: "Portogallo" },
  { code: "46", country: "Svezia" },
  { code: "47", country: "Norvegia" },
  { code: "45", country: "Danimarca" },
  { code: "358", country: "Finlandia" },
  { code: "353", country: "Irlanda" },
  { code: "1", country: "USA / Canada" },
  { code: "54", country: "Argentina" },
  { code: "55", country: "Brasile" },
  { code: "52", country: "Messico" },
  { code: "57", country: "Colombia" },
  { code: "58", country: "Venezuela" },
  { code: "51", country: "Perù" },
  { code: "593", country: "Ecuador" },
  { code: "62", country: "Indonesia" },
  { code: "63", country: "Filippine" },
  { code: "84", country: "Vietnam" },
  { code: "81", country: "Giappone" },
  { code: "82", country: "Corea del Sud" },
  { code: "61", country: "Australia" },
  { code: "27", country: "Sudafrica" },
  { code: "254", country: "Kenya" },
  { code: "233", country: "Ghana" },
  { code: "256", country: "Uganda" },
  { code: "255", country: "Tanzania" },
  { code: "237", country: "Camerun" },
  { code: "249", country: "Sudan" },
  { code: "251", country: "Etiopia" },
  { code: "252", country: "Somalia" },
  { code: "964", country: "Iraq" },
  { code: "961", country: "Libano" },
  { code: "962", country: "Giordania" },
  { code: "970", country: "Palestina" },
  { code: "972", country: "Israele" },
  { code: "966", country: "Arabia Saudita" },
  { code: "971", country: "Emirati Arabi Uniti" },
  { code: "973", country: "Bahrein" },
  { code: "974", country: "Qatar" },
  { code: "965", country: "Kuwait" },
  { code: "968", country: "Oman" },
  { code: "963", country: "Siria" },
  { code: "98", country: "Iran" },
  { code: "996", country: "Kirghizistan" },
  { code: "998", country: "Uzbekistan" },
  { code: "994", country: "Azerbaigian" },
  { code: "995", country: "Georgia" },
  { code: "374", country: "Armenia" },
  { code: "373", country: "Moldavia" },
  { code: "359", country: "Bulgaria" },
  { code: "421", country: "Slovacchia" },
  { code: "420", country: "Rep. Ceca" },
  { code: "36", country: "Ungheria" },
  { code: "354", country: "Islanda" },
  { code: "370", country: "Lituania" },
  { code: "371", country: "Lettonia" },
  { code: "372", country: "Estonia" },
  { code: "356", country: "Malta" },
  { code: "357", country: "Cipro" },
  { code: "378", country: "San Marino" },
  { code: "379", country: "Città del Vaticano" },
  { code: "376", country: "Andorra" },
  { code: "377", country: "Monaco" },
  { code: "352", country: "Lussemburgo" },
  { code: "218", country: "Libia" },
  { code: "222", country: "Mauritania" },
  { code: "231", country: "Liberia" },
  { code: "232", country: "Sierra Leone" },
  { code: "238", country: "Capo Verde" },
  { code: "239", country: "São Tomé e Príncipe" },
  { code: "240", country: "Guinea Equatoriale" },
  { code: "241", country: "Gabon" },
  { code: "242", country: "Congo (Brazzaville)" },
  { code: "243", country: "Congo (Kinshasa)" },
  { code: "244", country: "Angola" },
  { code: "245", country: "Guinea-Bissau" },
  { code: "248", country: "Seychelles" },
  { code: "250", country: "Ruanda" },
  { code: "253", country: "Gibuti" },
  { code: "257", country: "Burundi" },
  { code: "258", country: "Mozambico" },
  { code: "260", country: "Zambia" },
  { code: "261", country: "Madagascar" },
  { code: "263", country: "Zimbabwe" },
  { code: "264", country: "Namibia" },
  { code: "265", country: "Malawi" },
  { code: "266", country: "Lesotho" },
  { code: "267", country: "Botswana" },
  { code: "268", country: "eSwatini" },
  { code: "269", country: "Comore" },
  { code: "291", country: "Eritrea" },
];

/** Italy first (default), then rest sorted by country name. Use this in the booking form. */
export const PHONE_COUNTRY_CODES_SORTED: PhoneCountry[] = (() => {
  const italy = PHONE_COUNTRY_CODES.find((c) => c.code === "39");
  const rest = PHONE_COUNTRY_CODES.filter((c) => c.code !== "39").sort((a, b) =>
    a.country.localeCompare(b.country, "it")
  );
  return italy ? [italy, ...rest] : rest;
})();
